type Warehouse @collection(name: "warehouses") {
  name: String!
  address: Address!
}

type Category @collection(name: "categories") {
  label: String!
}

type Product @collection(name: "products") {
  name: String!
  description: String
  categoryID: Int
  images: [String]
  price: Int
  warehouse: Int
  quantity: Int
  backorderLimit: Int
  backordered: Boolean
}

type User @collection(name: "users") {
  uid: ID!
  address: Address
  role: String
  wishList: [Int]
  searchedItems: [String]
  clickedItems: [Int]
  usedTags: [String]
}

type Order @collection(name: "orders") {
  uid: Int!
  line: [ProductLine!]!
  status: String
  creationDate: Int!
  shipDate: Int
  shipAddress: Address!
  details: String
  deliveryMethod: String
  paymentMethod: String
  orderStatus: String
}

type Pages @collection(name: "pages") {
  products: ProductPage
}

type ProductPage {
  imageCarousel: [ImageCarousel!]!
}

type ImageCarousel @embedded {
  image: String!
  text: String
}

type Address @embedded {
  street: String!
  city: String
  state: String!
  zipCode: Int
}

type CustomerGroups {
  dateCreated: Int
  name: String
  description: String
  customers: [Int]!
}

type ProductLine @embedded {
  productID: Int!
  quantity: Int!
}

input SubmitOrderProductInput {
  productId: ID!
  quantity: Int!
}

type Query {
  allWarehouses: [Warehouse!]! @index(name: "all_warehouses")
  allCategories: [Category!]! @index(name: "all_categories")
  allProducts: [Product!]! @index(name: "all_products")
  allUsers: [User!]! @index(name: "all_users")
  allCustomers: [Customer!]! @index(name: "all_customers")
  allOrders: [Order!]! @index(name: "all_orders")
  allPages: [Pages!]! @index(name: "all_pages")
}

type Mutation {
  # Add Mutations
  addWarehouse: [Warehouse!]! @index(name: "all_warehouses")
  addCategory: [Category!]! @index(name: "all_categories")
  addProduct: [Product!]! @index(name: "all_products")
  addUser: [User!]! @index(name: "all_users")
  addCustomer: [Customer!]! @index(name: "all_customers")
  addOrder: [Order!]! @index(name: "all_orders")
  addPage: [Pages!]! @index(name: "all_pages")
  # Update Mutations
  updateWarehouse: [Warehouse!]! @index(name: "all_warehouses")
  updateCategory: [Category!]! @index(name: "all_categories")
  updateProduct: [Product!]! @index(name: "all_products")
  updateUser: [User!]! @index(name: "all_users")
  updateCustomer: [Customer!]! @index(name: "all_customers")
  updateOrder: [Order!]! @index(name: "all_orders")
  updatePage: [Pages!]! @index(name: "all_pages")
  # Example Mutation
  updateOrder(customerId: ID!, products: [SubmitOrderProductInput]): Order!
  @resolver(name: "update_order")
}
