type Warehouse @collection(name: "warehouses") {
  name: String!
  address: Address!
}

type Category @collection(name: "categories") {
  label: String!
}

type Product @collection(name: "products") {
  name: String!
  description: String
  categoryID: Int
  images: [String]
  price: Int
  warehouse: Int
  quantity: Int
  variants: [Int]
  reviews: [Reviews]
  questions: [Questions]
  enabled: Boolean
  featured: Boolean
}

type User @collection(name: "users") {
  uid: ID!
  address: Address
  role: String
  wishList: [Int]
  searchedItems: [String]
  clickedItems: [Int]
  usedTags: [String]
}

type Order @collection(name: "orders") {
  uid: Int!
  line: [ProductLine!]!
  status: String
  creationDate: Int!
  shipDate: Int
  shipAddress: Address!
  details: String
  deliveryMethod: String
  paymentMethod: String
  orderStatus: String
}

type Media @collection(name: "media") {
  productsCarousel: [ImageCarousel]
}

type Reviews {
  uid: String!
  name: String
  image: String
  time: String
  stars: Int
  review: String
}

type Questions {
  uid: String!
  name: String
  image: String
  time: String
  question: String
  anwsers: [Anwsers]
}

type Anwsers {
  uid: String!
  name: String
  image: String
  time: String
  anwser: String
}

type ImageCarousel @embedded {
  image: String!
  text: String
}

type Address @embedded {
  street: String!
  city: String
  state: String!
  zipCode: Int
}

type CustomerGroups {
  dateCreated: Int
  name: String
  description: String
  customers: [Int]!
}

type ProductLine @embedded {
  productID: Int!
  quantity: Int!
}

input SubmitOrderProductInput {
  productId: ID!
  quantity: Int!
}

type Query {
  allWarehouses: [Warehouse!]! @index(name: "all_warehouses")
  allCategories: [Category!]! @index(name: "all_categories")
  allProducts: [Product!]! @index(name: "all_products")
  allUsers: [User!]! @index(name: "all_users")
  allCustomers: [Customer!]! @index(name: "all_customers")
  allOrders: [Order!]! @index(name: "all_orders")
  allMedia: [Media!]! @index(name: "all_media")
  allFeatured: [Featured!]! @index(name: "all_featured")
}
